### ISSUE TITLE
Fatal error after installation if custom routes configured

### ISSUE THREAD

**Issue by louiswalch** [distantnative/retour-for-kirby#58] opened 2019-02-16 22:51 UTC
My Kirby config file contains some custom routes. After installation of this plugin I get a fatal error, removing the routes fixes it. Is this compatible with having routes?

```
Warning: array_merge(): Argument #2 is not an array in /.../kirby/src/Cms/AppPlugins.php on line 215

Fatal error: Uncaught TypeError: Return value of Kirby\Cms\App::extendRoutes() must be of the type array, null returned in /.../kirby/src/Cms/AppPlugins.php:215 Stack trace: #0 /.../kirby/src/Cms/AppPlugins.php(78): Kirby\Cms\App->extendRoutes(true, NULL) #1 /.../kirby/src/Cms/AppPlugins.php(320): Kirby\Cms\App->extend(Array) #2 /.../kirby/src/Cms/App.php(117): Kirby\Cms\App->extensionsFromOptions() #3 /.../kirby/src/Cms/App.php(455): Kirby\Cms\App->__construct() #4 /.../kirby/config/helpers.php(373): Kirby\Cms\App::instance() #5 /.../site/plugins/retour/index.php(15): kirby() #6 /.../kirby/src/Cms/AppPlugins.php(501): include_once('/Users/louiswal...') #7 /.../kirby/src/Cms/AppPlugins.php(467): Kirby\Cms\App->pluginsLoader() #8 /.../Kirb in /.../kirby/src/Cms/AppPlugins.php on line 215
```

**Comment by distantnative** [comment] 2019-02-17 08:29
> Is this compatible with having routes?

It seems like currently not - but that is a bug. It's of course intended to work alongside custom routes.

**Comment by distantnative** [comment] 2019-02-17 14:43
@louiswalch I can't reproduce it. Could you send me or post the content of your `config.php`?

**Comment by louiswalch** [comment] 2019-02-19 17:21
```

// config.php

return [
    'debug'     => true,
    'routes'    => require_once 'routes.php',
];


// routes.php

return [

    // Exhibition Filters
    [
        'pattern' => 'exhibitions/filter/(:any)/(:any?)',
        'action'  => function () {
            return page('exhibitions/filter');
        }
    ],
    // Legacy Exhibition Landing
    [
        'pattern' => 'projects/(:any?)/(:any?)/(:any?)',
        'action'  => function ($slug) {
            go('/exhibitions', 301);
        }
    ],
    // Legacy Exhibition Detail
    [
        'pattern' => 'view/exhibitions/(:any)',
        'action'  => function ($slug) {

            $page = page('exhibitions')->children()->filterBy('legacy_slug', $slug);

            // Redirect to new exhibition page.
            if ($page->count()) go($page->first()->url(), 301);
            
            // Show 404 message.
            return true;

        }
    ],

];

```

**Comment by distantnative** [comment] 2019-02-21 18:30
Works just fine for me. What PHP version are you using?

**Comment by louiswalch** [comment] 2019-02-21 18:57
Running 7.2.10, but also getting it with 7.1.22.

Does it have something to do with require_once another file. I've never used that syntax but copied it from Kirby docs somewhere about organizing routes into it's own file.

**Comment by distantnative** [comment] 2019-03-02 11:00
I still cannot reproduce it. Maybe it got fixed with other things. I'd please ask you to check again with beta.4 (to be released this weekend). Pleas re-open if you still encounter problems. Thanks.

**Closed by distantnative** 2019-03-02 11:00 UTC
Labels: type: bug 🐛
