### ISSUE TITLE
Routes config gets wiped

### ISSUE THREAD

**Issue by bvrp** [distantnative/retour-for-kirby#229] opened 2021-02-25 16:06 UTC
## Describe the bug
When adding a new entry by clicking on the "Add as redirect" on an entry under the Failures tab, when saving the new entry it a pop up window appears saying "Row is not defined". After dismissing the dialog, the new entry initially appears under the "Routes" tab, but a refresh of the page shows that the entire routes db that the plug uses is emptied.

Update: Adding new routes via the Routes tab also results in wiping out the Routes DB, except no error is show.

Update#2: Looks like what I thought were routes being added was only on the Routes tab local cached page DOM. No routes are actually being permanently saved. When refreshing the page, all routes added disappear.

Update#3: Ok- so routes are being written to redirects.yml by the plugin, however, reloading the plugin panel page in the browser causes it to overwrite the redirects.yml file with an empty one. It does not overwrite the "retour/log.sqlite" file though.

## Steps to reproduce

  1. Click on "Add as redirect" on one of the rows under the "Failures" tab.
  2. Add your new route in resulting dialog
  3. Save the new entry
  4. Pop up shows "Row is undefined"
  5. Click ok to dismiss dialog
  6. note that the new entry is shown in the routes tab.
  7. refresh browser page, or exit to kirby panel and go back to "Redirects"
  8. Note that all route entries are now gone/deleted.

## Expected behavior
That my new route is added without deleting all entries.

## Additional context
E.g. screenshots

## Specifications

  - Retour version: version is not indicated in the plugin but I just downloaded the plugin today from here.
  - Retour config options: default
  - Kirby version: 3.5
  - Browser: chrome

**Comment by chrfickinger** [comment] 2021-02-26 19:54
Issue #221 shows similar behavior. Maybe the issue is based on the same bug.

**Comment by bvrp** [comment] 2021-02-27 04:10
Yes, sure seems the same. From the looks of it, that thread you refer to was not resolved either, even though a "fix" was posted.

**Comment by distantnative** [comment] 2021-02-27 11:41
I can confirm the "Row not defined" and routes wiping bugs are not related as it seems.
I already found the "Row not defined" bug and fixed it.

On routes being wiped. The good news it, I just experienced it myself. So that's at least a chance of a lead :)

**Comment by distantnative** [comment] 2021-02-27 15:22
I invested some time into config file reading/saving improvements and unit tests.
I haven't run into the issue myself again since then. But not sure if I really caught it.
Anyone feeling brave to test the `develop` branch whether it really solves the problem?

**Comment by bvrp** [comment] 2021-02-27 15:48
I've installed your new version. Entries appear to be saved correctly. But there is also an "empty" route being saved somehow that shows up in the interface. When clicking on it to edit it- then clicking away to make the DLOG disappear without adding anything to the entry or saving it, an error "t.trim" is not a function appears.

An "empty" route entry should never appear in the Routes list for any reason. Preventing that should remove possibility of such an error.

**Comment by bvrp** [comment] 2021-02-27 15:56
Another weird ui issue I am seeing during this- clicking away from the dialog (not by clicking the checkmark in upper right) apparently still saves the entry. This should be handled as a "cancel" with no changes to be made. As it is currently, there is no way to "cancel" any changes made to the route DLOG.

Would be better to use proper ui conventions/process of "Save" "Cancel" etc.

**Comment by distantnative** [comment] 2021-02-27 16:26
@bvrp using the core drawer component which doesn't support a cancel event. It's just open or close. So we have to live with that and treat it as direct manipulation on the dataset, not one that can be canceled

**Comment by bvrp** [comment] 2021-02-27 16:57
Why even use a drawer to begin with. Non-cancellable drawer should never be the way to input data anywhere. Should be a pop-up really, no?

**Comment by chrfickinger** [comment] 2021-03-01 08:55
Just tested the develop branch. Seems placeholders, e.g. `(:all)` do not work anymore.

**Comment by chrfickinger** [comment] 2021-03-01 15:13
The error is still present in the develop version. The redirects delete themselves automatically. I can not reproduce when and what exactly happens. They are just empty at some point without being worked on.

**Comment by distantnative** [comment] 2021-03-01 17:37
I'm sorry guys, wish this wouldn't be so painful for you. I'll try to dig deeper.

**Comment by bvrp** [comment] 2021-03-01 18:31
> 
> 
> The error is still present in the develop version. The redirects delete themselves automatically. I can not reproduce when and what exactly happens. They are just empty at some point without being worked on.

Really? That's odd because it appears to be working fine now on my site. Odd indeed.

**Comment by nilshoerrmann** [comment] 2021-03-03 08:11
I'm not sure if this is related to the issue described here, but I noticed that after updating Retour and clearing Kirby's `media` folder, all redirects were unset on next panel load.

**Comment by nilshoerrmann** [comment] 2021-03-03 08:30
> Anyone feeling brave to test the develop branch whether it really solves the problem?

Editing an existing entry just caused all my routes to disappear using the `develop` branch. Nothing suspicious in the console. The log itself is still intact.

**Comment by johannschopplich** [comment] 2021-03-25 15:18
Running into the same issue myself. Does the `v4` branch contain a fix for this issue already? I'm ready to test. 🙂

**Comment by yatil** [comment] 2021-03-25 15:45
I am also affected by the issue – seems random, but I don’t know.

**Comment by nilshoerrmann** [comment] 2021-03-25 17:27
I'm not sure if that's related but I noticed that I have two Retour databases in my `logs` folder, `retour.sqlite` and `retour/log.sqlite`. Is that correct?

**Comment by distantnative** [comment] 2021-03-30 11:58
@johannschopplich aiming for the Easter break to finish v4

**Comment by guidoferreyra** [comment] 2021-03-30 14:43
I’m also having the issue of the config file being wiped.

**Comment by distantnative** [comment] 2021-04-03 13:02
I just released a first beta of Retour 4.0.0: https://github.com/distantnative/retour-for-kirby/releases/tag/4.0.0-beta.1

Since you are majorly affected by the flaws of v3, hopefully this will solve your problems. It would be great if some of you could try out this beta to see if this really solves the issues and to make sure we don't have new regressions.

Apologies for all the troubles and thanks for your patience and understanding!

**Comment by yatil** [comment] 2021-04-04 13:09
@distantnative How do you want us to report bugs/observations on the 4.0.0 beta?

**Comment by distantnative** [comment] 2021-04-04 15:47
@yatil best to just open new issues and mention that you're referring to the beta :)

**Comment by chrfickinger** [comment] 2021-04-08 11:17
The error is still present in v.4.0.0. I can not reproduce when and what exactly happens, but at one point the redirects delete themselves automatically. They are just empty at some point without being worked on.

**Comment by distantnative** [comment] 2021-04-08 11:53
Sigh :(

It would be really good to have any info on whether an error appears in the console or what actions lead up to this. I'm really trying to kill that big but it seems really difficult with it seeming so random

**Comment by guidoferreyra** [comment] 2021-04-25 17:39
@distantnative Since the beta 4.0 doesn’t [works for me](https://github.com/distantnative/retour-for-kirby/issues/243) what do you recommend to get a stable experience? Go back to 3.0?

**Comment by sebastiangreger** [comment] 2021-06-16 12:02
Hi; I just updated from 3.x to 4.0.0-beta.1 and while the `redirect.yml` was still intact, no routes were displayed in the panel.

After digging into the source code, it seems there is a typo in the [release notes](https://github.com/distantnative/retour-for-kirby/releases/tag/4.0.0-beta.1):

> Rename your config file to site/config/redirects.yml

should actually be `site/config/retour.yml`. I renamed the YML file and now 4.0 works smoothly :slightly_smiling_face:

**Comment by andreasfehn** [comment] 2021-06-25 16:32
> Hi; I just updated from 3.x to 4.0.0-beta.1 and while the `redirect.yml` was still intact, no routes were displayed in the panel.
> 
> After digging into the source code, it seems there is a typo in the [release notes](https://github.com/distantnative/retour-for-kirby/releases/tag/4.0.0-beta.1):
> 
> > Rename your config file to site/config/redirects.yml
> 
> should actually be `site/config/retour.yml`. I renamed the YML file and now 4.0 works smoothly 🙂

I also needed to change the first line ("routes" into "redirects:").
4.0.0-beta.1 seems to work (for me) now.  :)
Thanks for your incredible work, @distantnative!

**Comment by fvsch** [comment] 2021-07-13 10:42
Same problem of wiped `redirects.yml` here.
Tried the 4.0.0-beta1 but it doesn't seem to support `(:all)` placeholders correctly:

- If used as a partial match in a URL fragment, e.g. `(:all)wp-admin.php` instead of `(:all)/wp-admin.php`, they're just ignored.
- Otherwise, they tend blow up:

![Screenshot](https://user-images.githubusercontent.com/243601/125438676-a803435c-142d-43bc-9b5f-fc821562f389.png)

I'll try to stay on 3.0.1 and restore my `redirects.yml` from Git for now. :)

**Comment by derunterstrich** [comment] 2021-09-16 12:14
Hello,

I have the same problem, but I can recreate it relatively accurately. I create my routes and then copy the redirects.yml. If I wait ~20 minutes and press command + R, everything is gone. If I then restore my redirects.yml from the backup, everything is there again. 

I installed it via composer (version 3.0.1). Kirby has the latest version

**Comment by distantnative** [comment] 2021-12-29 12:55
This hopefully is solved by Retour 4.0 - [first beta](https://github.com/distantnative/retour-for-kirby/releases/tag/4.0.0-beta.1). Please help me test the beta, so that we can make sure that the actual release for sure doesn't suffer from the same problems as Retour 3 did.

Thanks everyone for your patience with this, I know it has been a pain point for many months.

**Closed by distantnative** 2021-12-29 12:55 UTC
Labels: bug 🐛
